# Используем официальный образ Airflow
FROM apache/airflow:2.7.1

# Переключаемся на пользователя airflow для установки пакетов
USER airflow

# Копируем requirements.txt
COPY requirements.txt /requirements.txt

# Устанавливаем дополнительные зависимости
# Игнорируем конфликты зависимостей airflow и pycaret, так как это демо
RUN pip install --no-cache-dir -r /requirements.txt
