FROM apache/airflow:2.11.0-python3.11

USER root

# Required by LightGBM (and some other ML libs) for OpenMP support
RUN apt-get update \
  && apt-get install -y --no-install-recommends libgomp1 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER airflow
